#!/bin/bash
FLUMEDIR=/usr/local/flume
FLUME_LOGFILE=$FLUMEDIR/flume_Daemon.log
FLUME_START=$FLUMEDIR/flumestartup.sh

whike [ 1 ]
  do
    FLUME_STATUS=`ps -ef |grep './conf/flumedzwl.conf' |grep -v grep |awk '{print $2}'`
      if [ -z "$FLUME_STATES" ] ;then 
          echo  "flume is not running,try to restart!"
         pushd $FLUMEDIR
	   nohup sh $FLUME_START
	 popd
       else
         echo "flume is running,checked `date`! " >> $FLUME_LOGFILE
      fi
     sleep 10
   done
